export function buildDomCache() {
            return {
                mainHeader:            document.getElementById('main-header-title'),
                notificationContainer: document.getElementById('notification-container'),
                modalContainer:        document.getElementById('modal-container'),
                kaizenForm:            document.getElementById('kaizen-form'),
                employeeSelect:        document.getElementById('employee-select'),
                yearSelect:            document.getElementById('year-select'),
                monthSelect:           document.getElementById('month-select'),
                submissionCount:       document.getElementById('submission-count'),
                filterYearChart:       document.getElementById('filter-year-chart'),
                filterSection:         document.getElementById('filter-section'),
                globalTargetInput:     document.getElementById('global-target'),
                topPerformersSection:  document.getElementById('top-performers-section'),
                reportTable:           document.getElementById('report-table'),
                addEmployeeBtn:        document.getElementById('add-employee-btn'),
                manageSectionsBtn:     document.getElementById('manage-sections-btn'),
                printBtn:              document.getElementById('print-btn'),
                exportJsonBtn:         document.getElementById('export-json-btn'),
                importBtn:             document.getElementById('import-btn'),
                importFileInput:       document.getElementById('import-file-input'),
                exportHtmlBtn:         document.getElementById('export-html-btn'),
                chartCanvas:           document.getElementById('kaizen-chart'),
                ocrImportBtn:          document.getElementById('ocr-import-btn'),
                generateEmailBtn:      document.getElementById('generate-email-btn'),
                exportReportBtn:       document.getElementById('export-report-btn'),
                exportEmailBannerBtn:  document.getElementById('export-email-banner-btn'),
            };
        }
